version: "3.9"

services:
  auth:
    build: .
    container_name: auth
    ports:
      - "8081:8081"
#    environment:
#      SERVER_PORT: 8081
#      DB_URL: ${DB_URL}
#      DB_USERNAME:  ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - pms-network

networks:
  pms-network:
    external: true
